[package]
name = "db_faker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
fake = "2.6"
clap = { version = "4", features = ["derive"] }
rand = "0.8"
indicatif = "0.17"
url = "2.5"
which = "8.0.0"
